### ISSUE TITLE
Using selectors in action creators.

### ISSUE THREAD

**Issue by MikeBarnhardt** [reactjs/reselect#187]
I searched the issues and didn't find a similar issue.

Is it possible to use a selector within an action creator?

For instance, if I had a forms reducer and wanted to get values from a specific `formId`.

```
export const updateModule = moduleId => (dispatch, getState) => {
  const moduleUpdates = formSelector(getState(), moduleId);
  return axios.post(`${API_URL}/modules/${moduleId}`, moduleUpdates);
};
```

I'm sure it would function (not throw), but are there any repercussions using the selector here?

**Comment by markerikson** [comment]
You are absolutely encouraged to do this!  Selectors are useful anywhere you have access to the Redux state tree.  That includes `mapState` functions, thunks, sagas, and even in reducers as well.  (And, they don't necessarily have to take the _entire_ tree either - you can have selectors that work on a subset of the tree too.)

Selectors generally provide three main benefits:

1. Encapsulation of potentially complex lookup logic
2. Encapsulation of specific data locations in the state tree
3. Possible memoization of lookups, which is particularly helpful if there's expensive work being done (such as filtering or sorting of data).

**Comment by MikeBarnhardt** [comment]
Awesome!

Thanks for the quick response. I converted a pretty bloated container component to use `reselect` today and it was so quick and easy to update that I figured why not just use it everywhere I can.

Thanks again!

**Comment by kevinjhanna** [comment]
@markerikson What would happens if selectors are used in actions, regarding "Sharing Selectors with Props Across Multiple Components"?

For example, when I have a state indexed by unique ids:

```node
const state = Immutable.Map({
    'id-1': {...},
    'id-2': {...},
})
```

The documentation leads me to believe I should create the selector with a factory each time I call an action, right? However, if I do so the memoization would not happen.

Right now, I'm using the example provided in https://github.com/reactjs/reselect#q-how-do-i-create-a-selector-that-takes-an-argument to fetch and transform things from the state which are indexed by a unique id.

I understand this approach is not optimal because if any sibling updates, it would recompute avery other sibling (in a lazy way).
