### ISSUE TITLE
[Question]What if we remove inputSelectors?

### ISSUE THREAD

**Issue by SunHuawei** [reactjs/reselect#221]
**I updated my question and description.** The original title is: *Why the inputSelectors is necessary?*

It is not easy every time you solve your performance issue by introducing `createSelector`.

For the example [here](https://github.com/reactjs/reselect#motivation-for-memoized-selectors), when we got a performance issue and we want to introduce `reselect` we should do these steps:

1. Add inputSelectors, `getVisibilityFilter` and `getTodos` for the example
2. Wrap inputSelectors and the calculate function
3. Rewrite the calculate function call

As you'v known, the signature of `createSelector` is this:

```javascript
createSelector(inputSelectors, calculateFunction)
```

I am wondering **why the inputSelectors is necessary**. I thought about it and did some research, I realized that **the selector expect the root node of `state` instead of some child of `state`**. The benefit is that it can be easy to call the selector.

**But, what if we accept the child of `state`?**

In my opinion, this would be enough for **Computing Derived Data**.

```javascript
cacheable(calculateFunction)
```

`cacheable` would wrap the calculate function, and return the wrapper function, a proxy. The proxy will hold the cache, and return the cached results if possible.

Use `cacheable`, we can get the same benefits by rewriting just one line of code. Just change

```javascript
const getVisibleTodos = (todos, filter) => {...}
```

to

```javascript
const getVisibleTodos = cacheable((todos, filter) => {...})
```

The call will not change
```javascript
    todos: getVisibleTodos(state.todos, state.visibilityFilter)
```

That above is just for `memorized`, yes, and for `composable`, actually, it is unnecessary if you wrap the composing functions with `cacheable`.

No composing need, just simple, easy and clear.

The `cacheable` code may look like this:

```javascript
const cacheable = (fn) => {
  /* May store args and result on fn like this:
   * fn.lastArgs = ...
   * fn.lastResult = ...
   */
  var lastArgs = []
  var lastResult = null

  const eq = (args1, args2) => {
    if (!args1 || !args2 || args1.length !== args2.length) return false
    return args1.every((arg, index) => arg === args2[index])
  }

  return (...args) => {
    if(eq(args, lastArgs)) {
      console.log('> from cache - ' + fn.name)
      return lastResult
    }

    const result = fn(...args)
    lastArgs = args
    lastResult = result
    return result
  }
}
```

[Here](http://jsbin.com/tawosi/edit?js,console) is a executable version.

Correct me if I have any misunderstading.

**Comment by SunHuawei** [comment]
Still not getting any response here.

I just made my thought [this lib(memoize.js)](https://github.com/SunHuawei/memoize.js) in case someone may want to try this. You may save a lot of time by choosing `memoize.js` over `reselect`.

**Comment by johnhaley81** [comment]
One of the nice things about using `reselect` and just selectors in general is that _all selectors have the same input_. Which means that selectors calling other selectors and composing them together is trivial. *Everything* is a product of the state and a props object (which is optional).

By removing that, you now have a requirement to know an implementation detail of any and all selectors that you call. In your example, you must know that that before you call `getVisibleTodos` you have to extract out slices of the state and what order to pass them in.

Before, you can just call `getVisibleTodos` with the state and internally it figured out what slices of the state it needed.

The reason why this is important is because code and requirements change over time. The less I have to know about how a function does its job the less work I have to do in other code to maintain functionality.

Take the above example. We have `getVisibleTodos` as a product of 2 properties of the state: `state.todos` and `state.filter`. Now, let's assume that the product is expanded to allow grouping of todo items and you can also hide the groups in addition to specific todo items.

Now the `getVisibleTodos` would take another parameter (which could be derived from the state) and everywhere that calls that function now has to update and also take in that value in order to pass it through. Top level functions/selectors now need to pull out more and more values for all subcalls and need to know exactly what each function takes all the way down to the lowest level selector that will be called by it.

This will make modifying selectors for any sufficiently large codebase a lot more work than they have to be.

So yes, composition is one of _if not the_ main reason to use reselect over something like https://lodash.com/docs/#memoize. If this seems superfluous to you then in addition to not needing reselect, your app [might not need redux](https://medium.com/@dan_abramov/you-might-not-need-redux-be46360cf367) either.
