### ISSUE TITLE
Composing selectors: lack of memoization

### ISSUE THREAD

**Issue by pke** [reactjs/reselect#236]
This example is given in the docs:

```es6
const makeMapStateToProps = () => {
  const getVisibleTodos = makeGetVisibleTodos()
  const mapStateToProps = (state, props) => {
    return {
      todos: getVisibleTodos(state, props)
    }
  }
  return mapStateToProps
}
```

However, calling `makeGetVisibleTodos()` will always return a new selector. Where does the memoization come into play here? The resulting `getVisibleTodos` will always operate on a new state, nothing is memoized. Or what am I missing here?

**Comment by markerikson** [comment]
That's an example of the "factory function syntax" supported by the React-Redux `connect` function.  If a `mapState` function returns another function the first time it's called, that returned function is used as the "real" `mapState`.  So, that example creates a selector function instance that is unique to that closure, and therefore unique to the current component instance.  That means it will memoize correctly, even if multiple instances of the same component type are being rendered, whereas just re-using the same selector instance across multiple instances of a component would _not_ memoize because they'd likely all pass in different props values.

I wrote up an example of using the factory `mapState` syntax here: https://www.reddit.com/r/reactjs/comments/5dxasp/any_deepdiveadvanced_tutorials_on_reselect/ .
