### ISSUE TITLE
Multiple components using the same selector

### ISSUE THREAD

**Issue by sht5** [reactjs/reselect#259]
i have a lot of components which are each connected (in their stateProps) to a certain selector(implemented with reselect, lets refer to it as selector A). every time one of selector A's params(also selectors lets refer to as A,B,C) changes,  selector A recalculates and is invoked separately for each connected component. as this calculation is intensive this costs me a lot in performance. is there a way to avoid this and calculate once for all?
thanks

**Comment by markerikson** [comment]
Yep, this is addressed in the FAQ in the front of the repo.  See https://github.com/reactjs/reselect#q-can-i-share-a-selector-across-multiple-components , and my similar explanation at https://www.reddit.com/r/reactjs/comments/5dxasp/any_deepdiveadvanced_tutorials_on_reselect/ .

**Comment by sht5** [comment]
Either I'm not understanding this right or I'm talking about a slightly different problem.you and the docs are talking about using a factory to allow each component to have its own memoization and 'personal' selector. In my case i have a lot of components which get the same props at the same time. The selector is calculated again and again for each component.

**Comment by markerikson** [comment]
Can you give an example of how your selectors are defined?  The point of memoization is that _if_ all the inputs are the same, then any calculations are skipped and the previously determined value is returned.  

There's definitely something about your situation I'm not quite getting.  First you said that the inputs to SelectorA keep changing, then you said that "a lot of components get the same props at the same time".

Really need to see some code to better understand what's going on here.

**Comment by sht5** [comment]
Ok I'll add some code when i get to the office

**Comment by sht5** [comment]
Hey,
i made a gist here https://gist.github.com/sht5/d496d1c988e77e88daa8e453038b7eed
start from things_selector file: the selector "FilteredThingIDsSelector" which depends on other selectors is used as a prop to different components in the app. they all use redux's mapStateToProps method as in the pageWithFilterPanelContainer component.
when one of the filteredThingHierarchySelector ( which FilteredThingIDsSelector depends upon) params changes i see that the filteredThingHierarchySelector selector is called for each component that uses FilteredThingIDsSelector independently.
I don't see why it should be called once for every component when the param changes once.
please notice i'm using createDeepEqualSelector as in the documention with lodash's isEqual method. let me know if anything is unclear.
thanks

**Comment by markerikson** [comment]
Okay, I see your main problem.

You're calling `toJS()` in your "input selectors" such as `thingHierarchySelector `.  This is a **BAD IDEA** for several reasons.  It will return new object references _every_ time it is called, _and_ `toJS()` is the single most expensive operation in the Immutable.js API.  I have links to several articles discussing why calling `toJS()` should be avoided in the [React Performance#Immutable Data](https://github.com/markerikson/react-redux-links/blob/master/react-performance.md#immutable-data) section of my [React/Redux links list](https://github.com/markerikson/react-redux-links).

The second problem is that you're not making good use of Reselect's memoization.  You could sorta get away with calling `toJS()` inside of your selectors, _if_ they were properly memoized.  But, not only are most of your selectors _not_ memoized, you're also doing multi-level lookups every time.  A properly memoized version of `thingsHierarchySelector` would look like:

```js
export const selectThingsReducer = state => state[consts.TOP_LEVEL_STATE_REDUCERS.THINGS_REDUCER];
const selectThingsHierarchy = createSelector(
    selectThingsReducer,
    (thingsReducer) => thingsReducer.get(consts.STATE_INNER_OBJECT_NAMES.THINGS_HIERARCHY)
);

const selectThingsHierarchyJS = createSelector(
    selectThingsHierarchy,
    (thingsHierarchy) => thingsHierarchy.toJS()
);
```

Third, a stylistic issue that also relates to performance.  I see that you've copy-pasted code like `(state) => state[consts.TOP_LEVEL_STATE_REDUCERS.FILTERING_THING_CAPABILITIES_REDUCER]` in every selector.  That's very hard to read, and also doesn't help with memoization.  Instead, you should have one selector that encapsulates looking up that state field, and then re-use that selector as an input to all the others, like:

```js
export const selectFilteringReducer = (state) => state[consts.TOP_LEVEL_STATE_REDUCERS.FILTERING_THING_CAPABILITIES_REDUCER];

export const selectAllOfLeftNavSelectedFilters = createSelector(
    selectFilteringReducer,
    (filteringReducer) => filteringReducer.get(consts.STATE_INNER_OBJECT_NAMES.LEFT_NAV_SELECTED_FILTER_PATHS).toJS();
);

export const selectSelectedSearchBarTerm = createSelector(
    selectFilteringReducer,
    (filteringReducer) => filteringReducer.get(consts.STATE_INNER_OBJECT_NAMES.SEARCH_BAR_TERM).toJS();
);
```

So, ultimately this is an issue with improper use of selector functions and Reselect.  Restructuring your selector functions so that they actually are created using memoization will fix the problem.

**Comment by sht5** [comment]
wow mark thanks so much for the analysis and help. much appreciated.
i think i will get rid of immutable.js completely, i'm using it heavily
around the app and it might be one of the causes i'm experiencing such bad
performance.
thanks

**Comment by markerikson** [comment]
Yeah, I personally advise against use of Immutable.js in general (personal opinion).  [I wrote up my reasons in a Reddit comment a while back](https://www.reddit.com/r/javascript/comments/4rcqpx/dan_abramov_redux_is_not_an_architecture_or/d51g4k4?context=3).

**Comment by sht5** [comment]
Hey again mark,
I'm implementing your suggestions,
wanted to ask about replacing default memoize with a better function. when
is this actually effective? when my selector-inputs aren't primitive
objects ?
thanks

**Comment by markerikson** [comment]
Ah... I think you may be confusing two different things.

The default _memoization_ capability is to only save the last input+output seen by the function (ie, a cache size of 1).  You can change that by using `createSelectorCreator` and passing in your own memoization function instead of Reselect's `defaultMemoize`.

However, part of that memoization is the _comparison_ process - "how do I decide if these two values are equal?".  If you do use `createSelectorCreator(defaultMemoize)`, you can also pass in a custom equality check function such as Lodash's `isEqual`, as you were doing in your example.  

I personally don't see a need to change the default equality checking logic unless you have a _very_ specific use case.  If you're writing an idiomatic Redux application, you should be doing immutable data updates and be able to compare values with reference checks, whether you're using plain JS objects and arrays or Immutable.js Maps and Lists.

**Comment by sht5** [comment]
Great.
I implemented the changes last night and performance was improved
significantly!
Thanks again for taking the time to guide me, i can't thank you enough.
