### ISSUE TITLE
Noob question

### ISSUE THREAD

**Issue by albert-olive** [reactjs/reselect#268]
Hi, 

If I have defined my chat state as this:

    chat: {
      status: {
        connected: false,
        logged: false,
        pending: false,
        error: {},
        unreadMessages: 0,
      },
      ui: {
        activeItem: '',
        itemsPerRequest: 20,
        shouldShowLoad: true,
      },
     ...

Do I have to create one selector for each one? For example:

    const selectChatState = () => ({ chat }) => chat;

    const getChatStatusConnected = () => createSelector(
      selectChatState(),
      ({ status }) => status.connected
    );

Or just create groups of objects, like `status`, `ui`, etc, or chat object itself.

I don't know If doing that way (grouping it), will be recomputed more than having on selector for each one.

Thanks and sorry If this question has been answered, although I didn't find it.

**Comment by markerikson** [comment]
For best results, you would want to create selectors for each level of nesting.  Note that selectors for top-level items can be trivial functions, since there's no need to memoize those.  Also, there's no need to define a selector as a function that returns a plain function, the way you have `selectChatState`.  It _can_ be useful to define a selector as a function that returns the result of `createSelector` in some cases, but that's an optimization you don't have to worry about right away.

So, for example, I would have:

```js
const selectChat = (state) => state.chat;
const selectChatStatus = createSelector(
    selectChat,
    (chat) => chat.status
);

const selectChatUnreadMessages = createSelector(
    selectChatStatus,
    (chatStatus) => chatStatus.unreadMessages
);
```

**Comment by albert-olive** [comment]
Ok, thank you for the answer. Now I get it ;)
