### ISSUE TITLE
How to reduce number of re-computations with dynamic input arguments

### ISSUE THREAD

**Issue by contactjaisai** [reactjs/reselect#275]
I have a selector that use dynamic input arguments.
```javascript
const getId = (_,id) => id;
export const getUserData =
                createSelector(getState, getId, (state, id) => _.find(state, {id}));
```

Here are my test cases:
```javascript
getUserData(state, 'abc');
getUserData(state, 'def');
expect(getUserData.recomputations()).toEqual(2); // till here it works fine
getUserData(state, 'abc');
// I want to achieve the below use case, when you pass id as 'abc',
// it should return the memoized result.
expect(getUserData.recomputations()).toEqual(2); // this fails with recomputations as 3
```

**Comment by markerikson** [comment]
You would need to use [`createSelectorCreator`](https://github.com/reactjs/reselect#createselectorcreatormemoize-memoizeoptions) to create a customized version of `createSelector` with a larger cache size.  With the default cache size of 1, a selector created by `createSelector` will always recalculate when it sees different arguments than the last time it was called.

**Comment by contactjaisai** [comment]
@markerikson I went through createSelectorCreator api, not sure how to achieve my use case using createSelectorCreator. Can you please send me some sample?

**Comment by markerikson** [comment]
See this example in the README: https://github.com/reactjs/reselect#use-memoize-function-from-lodash-for-an-unbounded-cache

**Comment by toomuchdesign** [comment]
Hi @contactjaisai, hi @markerikson !
the example above is the perfect use case for [re-reselect](https://github.com/toomuchdesign/re-reselect).

It is just a tiny wrapper around `reselect` and would solve the lost memoization problem by memoizing the selectors themselves (not their result). It can replace any existing selector since it  `reselect` interface.

From *v1.0.0* it comes with **custom cache management**, too!

**Comment by contactjaisai** [comment]
@toomuchdesign Yeah, I've used it already.. It worked fine.
