### ISSUE TITLE
Stopping props recalculating the selector each time

### ISSUE THREAD

**Issue by dagda1** [reactjs/reselect#282]
I have this selector:

```
export const resolvedAddressSelector = (
  state: State,
  props: Props
): Address => {
  const { isEditMode, editIndex } = props;

  if (!isEditMode) {
    return clone(initialState.applicant.currentAddress);
  }

  return getAddressByIndex(editIndex, state);
};

export const currentAddressSelector = createSelector(
  resolvedAddressSelector,
  (address: Address): Address => {
    return address;
  }
);
```

Which I access in `mapStateToProps` like this:

`previousAddress: previousAddressSelector(state, props),`

I am having trouble understanding the documentation that states that if a function is passed to `connect` that returns a `mapStateToProps` then:

> If we pass makeMapStateToProps to connect, each instance of the VisibleTodosList container will get its own mapStateToProps function with a private getVisibleTodos selector. Memoization will now work correctly regardless of the render order of the VisibleTodoList containers.

I don't understand how returning a function will make memoization suddenly work and when I tried it, I can still see the selector recalculating each time.

What is `VisibleTodoListContainer` container?

**Comment by markerikson** [comment]
It's two things, one on the Reselect side, and one on the React-Redux side.

Reselect selectors, by default, only memoize on the latest inputs.  If you change _any_ input, it calculates the new values, and saves the current inputs/output as its size-1 cache.  

But, let's say you've got some list items like:

```js
<List>
    <ListItem id={1} />
    <ListItem id={2} />
</List>
```

And ListItem's `mapState` function looks like:

```js
const listItemMapState = (state, ownProps) => {
    const item = selectListItem(state, ownProps.id);
    return {item};
}
```

In that case, the selector will never memoize "properly", because first it gets called with id 1, then id 2, etc, so it will always recalculate its output.

The "factory function" syntax supported by `connect` lets you create unique instances of a selector for each instance of a component, so that each selector instance will memoize based on a consistent set of inputs.

I [wrote up an example of doing this](https://www.reddit.com/r/reactjs/comments/5dxasp/any_deepdiveadvanced_tutorials_on_reselect/) a while back, which you might want to look at.

**Comment by dagda1** [comment]
Thank you for your reply, if we use this example in your post:

```
function makeMapState(originalState, originalOwnProps) {
    const uniqueSelectorInstance = makeSelectorForThisItem();

    return function actualMapState(state, ownProps) {
        const dataForThisItem = uniqueSelectorInstance(state, ownProps.itemId);

        return {item : dataForThisItem};
    }    
}
```

You pass in `originalState` and `originalOwnProps` but you never use them.  The only way I can see this working any differently is if `originalOwnProps` was used to get the `itemId`.

Am I missing something?

**Comment by markerikson** [comment]
@dagda1 : yeah.  `connect` will call this the first time with `originalState` (and `originalProps`, if specified).  However, _if_ the `mapState` function returns another function the first time it's called, then the returned function is used as the "real" `mapState` after that.

So, on first call, this will create a unique selector for _this_ specific component instance, and then that selector gets used in the "real" `mapState`.
