### ISSUE TITLE
Mistake in reselect docs 

### ISSUE THREAD

**Issue by kutsokon** [reactjs/reselect#295]
https://github.com/reactjs/reselect#containersvisibletodolistjs-3
```
import { connect } from 'react-redux'
import { toggleTodo } from '../actions'
import TodoList from '../components/TodoList'
import { makeGetVisibleTodos } from '../selectors'

const makeMapStateToProps = () => {
  const getVisibleTodos = makeGetVisibleTodos()
  const mapStateToProps = (state, props) => {
    return {
      todos: getVisibleTodos(state, props)
    }
  }
  return mapStateToProps
}

const mapDispatchToProps = (dispatch) => {
  return {
    onTodoClick: (id) => {
      dispatch(toggleTodo(id))
    }
  }
}

const VisibleTodoList = connect(
  makeMapStateToProps,
  mapDispatchToProps
)(TodoList)

export default VisibleTodoList
```

Here ```makeMapStateToProps``` is just a function that returns ```mapStateToProps``` function, then we have ```makeMapStateToProps``` as an argument in ```connect``` (react-redux). It seems to be executed and not only passed. Am I right?

**Comment by markerikson** [comment]
Nope, that is correct.  `connect()` supports this "factory function" syntax as an optimization.  If the first call to your `mapState` or `mapDispatch` function returns a function instead of an object, it uses that returned function as the "real" `mapWhatever` function.  That allows you to create per-instance-specific selectors in the closure.
