### ISSUE TITLE
typo in the first example code in README.md

### ISSUE THREAD

**Issue by matt8754** [reactjs/reselect#522]
const selectTax = createSelector(
  selectSubtotal,
  selectTaxPercent,
  (subtotal, taxPercent) => subtotal * (taxPercent / 100)
)

This should be:

const taxSelector = createSelector(
  selectSubtotal,
  selectTaxPercent,
  (subtotal, taxPercent) => subtotal * (taxPercent / 100)
)

**Comment by markerikson** [comment]
Appreciate the issue, but I don't think there's a typo.

I actually just went through and renamed all the variables in the README to follow our recommend naming convention of `selectX` a couple days ago.

We haven't tried to update the Codepen, so if the variables look different between the README and the Codepen, that's why.

**Comment by matt8754** [comment]
> Appreciate the issue, but I don't think there's a typo.
> 
> I actually just went through and renamed all the variables in the README to follow our recommend naming convention of `selectX` a couple days ago.
> 
> We haven't tried to update the Codepen, so if the variables look different between the README and the Codepen, that's why.

In this case,

const selectTotal = createSelector(
  selectSubtotal,
  taxSelector,  <== this should be selectTax, :-)
  (subtotal, tax) => ({ total: subtotal + tax })
)
